name: AWS CLI test

on:
  push:
    paths:
      - 'hello.txt'
      - '.github/workflows/aws_test.yml'

jobs:
  aws-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Upload file to S3
      run: |
        aws s3 cp hello.txt s3://dev-cli-bucket-01/
