name: Basic CI with Python

on:
  push:
    paths:
      - '.github/workflows/python_test.yml'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Python script
      run: |
        echo "Running Python inline..."
        python -c "print('Hello from GitHub Actions 👋')"
